class Persistent {
  static List<String> jobCategoryList = [
    'architect',
    'brick mason',
    'Construction assistant',
    'construction manager',
    'construction inspector',
    'cost estimator',
    'crame operator',
    'quality assurance',
    'concrete finisher',
    'civil engineer',
    'equipment operator',
    'inspector',
    'general labourer',
    'foreman',
    'scheduler',
    'surveyor',
    'field engineer',
    'tile setter',
    'flooring installer',
    'glazier',
    'estimator',
    'project manager',
    'safety manager',
    'structural engineer',
    'carpenters',
    'ironworkers',
    'plumbers',
    'painters',
    'pipefitters',
    'roofers',
    'electricians',
    'welders',
    'drywall installers',


    ];
}
